# Generated by Django 3.1.1 on 2020-10-31 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('constituency', models.IntegerField(default=100, primary_key=True, serialize=False)),
                ('constituency_name', models.CharField(max_length=20)),
                ('constituency_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20)),
                ('uemail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('upassword', models.CharField(max_length=20)),
                ('umobile', models.IntegerField()),
                ('uconsname', models.CharField(default='basavangudi', max_length=20)),
                ('const', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PEPapp.constituency')),
            ],
        ),
    ]
