# Generated by Django 3.1.1 on 2020-11-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEPapp', '0002_constituency_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='constituency_description',
            field=models.CharField(max_length=1500),
        ),
    ]
