# Generated by Django 3.1.1 on 2020-11-02 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PEPapp', '0003_auto_20201102_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector', models.IntegerField(primary_key=True, serialize=False)),
                ('sector_name', models.CharField(max_length=20)),
                ('sector_scope', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='News_Feed',
            fields=[
                ('feed_id', models.IntegerField(primary_key=True, serialize=False)),
                ('feed_title', models.CharField(max_length=20)),
                ('feed_description', models.CharField(max_length=20)),
                ('feed_date', models.DateField()),
                ('constituency_name', models.CharField(max_length=20)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PEPapp.constituency')),
            ],
        ),
    ]
