# Generated by Django 3.1.1 on 2020-11-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEPapp', '0006_auto_20201102_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituency',
            name='file',
        ),
        migrations.AlterField(
            model_name='user',
            name='umobile',
            field=models.IntegerField(null=True),
        ),
    ]
