# Generated by Django 3.1.1 on 2020-11-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEPapp', '0008_auto_20201104_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='umobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
