# Generated by Django 3.1.1 on 2020-11-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEPapp', '0009_auto_20201104_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_feed',
            name='feed_id',
        ),
        migrations.AddField(
            model_name='news_feed',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
