# Generated by Django 3.1.1 on 2020-11-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PEPapp', '0011_auto_20201105_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_feed',
            name='feed_date',
        ),
    ]
